sudo: required
services:
  - docker

before_install:
  - docker build -t mstandley/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true mstandley/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "eu-west-1"
  app: "mark-test"
  env: "MarkTest-env"
  bucket_name: "elasticbeanstalk-eu-west-1-146510325632"
  bucket_path: "mark-test"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: 
    secure: "$AWS_SECRET_KEY"

