sudo: required
services:
  - docker

before_install:
  - docker build -t mstandley/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true mstandley/docker-react npm run test -- --coverage
